# NEC VE cross compilation. All artifacts remain inside the project.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR ve)
set(CMAKE_C_COMPILER /opt/nec/ve/bin/ncc)
set(CMAKE_CXX_COMPILER /opt/nec/ve/bin/nc++)
set(CMAKE_C_FLAGS_INIT "-O2 -std=c11 -fdiag-inline=0 -fdiag-vector=0")
set(CMAKE_CXX_FLAGS_INIT "-O2 -std=c++17 -fdiag-inline=0 -fdiag-vector=0")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,-rpath-link,/opt/nec/ve/ncc/5.4.1/lib")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-Wl,-rpath-link,/opt/nec/ve/ncc/5.4.1/lib")
set(CMAKE_C_COMPILE_FEATURES c_std_11)
set(CMAKE_CXX_COMPILE_FEATURES cxx_std_17)
set(CMAKE_C_STANDARD_COMPUTED_DEFAULT 11)
set(CMAKE_CXX_STANDARD_COMPUTED_DEFAULT 17)
set(CMAKE_C_EXTENSIONS_COMPUTED_DEFAULT OFF)
set(CMAKE_CXX_EXTENSIONS_COMPUTED_DEFAULT OFF)
