# NCC's CMake feature probe reports only the configured C++17 dialect.
# Apply the valid earlier standard features after project()/compiler loading.
list(APPEND CMAKE_CXX_COMPILE_FEATURES cxx_std_11 cxx_std_14)
function(sd_baseline_overrides)
    get_filename_component(project_root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
    set(overlay "${project_root}/build/sd-baseline-overlay")
    # NCC emits dependency files containing only the translation unit here.
    # Explicit dependencies prevent stale objects after overlay header edits.
    file(GLOB image_headers CONFIGURE_DEPENDS "${overlay}/*.h" "${overlay}/*.hpp")
    list(APPEND image_headers "${project_root}/src/ve_sd_turbo_support.h"
        "${project_root}/src/ve_sd_turbo_stages.h" "${project_root}/src/ve_sd_turbo_profile.h")
    if(TARGET zip)
        target_compile_definitions(zip PRIVATE _GNU_SOURCE)
    endif()
    if(TARGET ggml-cpu)
        if(SD_GGML_OPENMP)
            target_compile_definitions(ggml-cpu PRIVATE GGML_USE_OPENMP)
            target_compile_options(ggml-cpu PRIVATE -fopenmp)
        endif()
        get_target_property(sources ggml-cpu SOURCES)
        list(REMOVE_ITEM sources "ggml-cpu.c" "${CMAKE_SOURCE_DIR}/ggml/src/ggml-cpu/ggml-cpu.c")
        list(APPEND sources "${overlay}/sd-ggml-cpu.c" "${project_root}/src/ve_sd_turbo_gelu.c" "${project_root}/src/ve_sd_turbo_silu.c" "${project_root}/src/ve_sd_turbo_softmax.c" "${project_root}/src/ve_sd_turbo_softmax_sum.c" "${project_root}/src/ve_sd_turbo_im2col.c" "${project_root}/src/ve_sd_turbo_im2col_rows.c")
        set_source_files_properties("${project_root}/src/ve_sd_turbo_gelu.c" "${project_root}/src/ve_sd_turbo_silu.c" "${project_root}/src/ve_sd_turbo_softmax.c"
            TARGET_DIRECTORY ggml-cpu PROPERTIES COMPILE_OPTIONS "-O2;-fno-fast-math;-fno-associative-math;-fno-reciprocal-math;-mvector-intrinsic-check;-mvector-floating-divide-instruction;-fdiag-vector=2")
        set_source_files_properties("${project_root}/src/ve_sd_turbo_softmax_sum.c"
            TARGET_DIRECTORY ggml-cpu PROPERTIES COMPILE_OPTIONS "-O1;-fno-fast-math;-fno-associative-math;-mno-vector")
        set_source_files_properties("${project_root}/src/ve_sd_turbo_im2col.c" "${project_root}/src/ve_sd_turbo_im2col_rows.c"
            TARGET_DIRECTORY ggml-cpu PROPERTIES COMPILE_OPTIONS "-O2;-fno-fast-math;-fdiag-vector=2")
        set_property(TARGET ggml-cpu PROPERTY SOURCES "${sources}")
        target_sources(ggml-cpu PRIVATE "${project_root}/src/ve_sd_turbo_binary.c")
        target_sources(ggml-cpu PRIVATE "${project_root}/src/ve_sd_turbo_cont_transpose.c")
        target_sources(ggml-cpu PRIVATE "${project_root}/src/ve_sd_turbo_softmax_scale.c")
        target_sources(ggml-cpu PRIVATE "${project_root}/src/ve_sd_turbo_group_norm.c")
        set_source_files_properties("${project_root}/src/ve_sd_turbo_group_norm.c"
            TARGET_DIRECTORY ggml-cpu PROPERTIES COMPILE_OPTIONS "-O2;-fno-fast-math;-fno-associative-math;-fdiag-vector=2")
        set_source_files_properties("${project_root}/src/ve_sd_turbo_softmax_scale.c"
            TARGET_DIRECTORY ggml-cpu PROPERTIES COMPILE_OPTIONS "-O2;-fno-fast-math;-fno-associative-math;-fdiag-vector=2")
        set_source_files_properties("${project_root}/src/ve_sd_turbo_cont_transpose.c"
            TARGET_DIRECTORY ggml-cpu PROPERTIES COMPILE_OPTIONS "-O2;-fno-fast-math;-fno-associative-math;-fdiag-vector=2")
        set_source_files_properties("${project_root}/src/ve_sd_turbo_binary.c"
            TARGET_DIRECTORY ggml-cpu PROPERTIES COMPILE_OPTIONS "-O2;-fno-fast-math;-fno-associative-math;-fdiag-vector=2")
        target_include_directories(ggml-cpu PRIVATE "${CMAKE_SOURCE_DIR}/ggml/src/ggml-cpu")
    endif()
    if(TARGET ggml-blas)
        if(SD_NLC_OPENMP)
            target_compile_options(ggml-blas PRIVATE -fopenmp)
        endif()
        get_target_property(sources ggml-blas SOURCES)
        set(replacements)
        foreach(source IN LISTS sources)
            get_filename_component(name "${source}" NAME)
            if(name STREQUAL "ggml-blas.cpp")
                list(APPEND replacements "${overlay}/sd-ggml-blas.cpp")
            else()
                list(APPEND replacements "${source}")
            endif()
        endforeach()
        set_property(TARGET ggml-blas PROPERTY SOURCES "${replacements}")
        target_sources(ggml-blas PRIVATE "${project_root}/src/ve_sd_turbo_gemm_pack.c")
        set_source_files_properties("${project_root}/src/ve_sd_turbo_gemm_pack.c"
            TARGET_DIRECTORY ggml-blas PROPERTIES COMPILE_OPTIONS "-O2;-fno-fast-math;-fno-associative-math;-fdiag-vector=2")
        target_include_directories(ggml-blas PRIVATE "${overlay}"
            "${CMAKE_SOURCE_DIR}/ggml/src/ggml-blas" "${CMAKE_SOURCE_DIR}/ggml/src")
        set_source_files_properties("${overlay}/sd-ggml-blas.cpp"
            TARGET_DIRECTORY ggml-blas PROPERTIES OBJECT_DEPENDS "${overlay}/sd_profile.h")
    endif()
    if(TARGET ggml-base)
        get_target_property(sources ggml-base SOURCES)
        set(replacements)
        foreach(source IN LISTS sources)
            get_filename_component(name "${source}" NAME)
            if(name STREQUAL "ggml-backend.cpp")
                list(APPEND replacements "${overlay}/sd-ggml-backend.cpp")
            else()
                list(APPEND replacements "${source}")
            endif()
        endforeach()
        set_property(TARGET ggml-base PROPERTY SOURCES "${replacements}")
        target_include_directories(ggml-base PRIVATE "${CMAKE_SOURCE_DIR}/ggml/src")
        set_source_files_properties("${overlay}/sd-ggml-backend.cpp"
            TARGET_DIRECTORY ggml-base PROPERTIES OBJECT_DEPENDS "${overlay}/sd_profile.h")
    endif()
    if(TARGET stable-diffusion)
        # This fixed older framework requires C++11, unlike the modern branch.
        target_compile_options(stable-diffusion PRIVATE "$<$<COMPILE_LANGUAGE:CXX>:-std=c++11>")
        get_target_property(sources stable-diffusion SOURCES)
        set(replacements)
        foreach(source IN LISTS sources)
            get_filename_component(name "${source}" NAME)
            if(name STREQUAL "stable-diffusion.cpp" OR name STREQUAL "upscaler.cpp")
                continue()
            endif()
            if(EXISTS "${overlay}/${name}")
                list(APPEND replacements "${overlay}/${name}")
            else()
                list(APPEND replacements "${source}")
            endif()
        endforeach()
        foreach(component clip unet vae)
            list(APPEND replacements "${project_root}/src/ve_sd_turbo_${component}.cpp")
            set_source_files_properties("${project_root}/src/ve_sd_turbo_${component}.cpp"
                TARGET_DIRECTORY stable-diffusion PROPERTIES COMPILE_OPTIONS "-O0;-fno-inline")
        endforeach()
        list(APPEND replacements "${overlay}/sd_clip_vocab.c")
        set_property(TARGET stable-diffusion PROPERTY SOURCES "${replacements}")
        foreach(source IN LISTS replacements)
            if(source MATCHES "\\.cpp$")
                set_source_files_properties("${source}" TARGET_DIRECTORY stable-diffusion
                    PROPERTIES OBJECT_DEPENDS "${image_headers}")
            endif()
        endforeach()
        target_include_directories(stable-diffusion BEFORE PRIVATE "${overlay}" "${project_root}/src")
        set_source_files_properties("${overlay}/model.cpp"
            TARGET_DIRECTORY stable-diffusion PROPERTIES COMPILE_OPTIONS "-O0;-fno-inline")
    endif()
    if(TARGET sd)
        add_library(sd-png-ve STATIC "${project_root}/src/ve_sd_turbo_png.cpp")
        target_include_directories(sd-png-ve PRIVATE "${CMAKE_SOURCE_DIR}/thirdparty")
        target_compile_options(sd-png-ve PRIVATE -std=c++11 -O2 -fno-fast-math -fno-associative-math -fdiag-vector=2)
        set_source_files_properties("${project_root}/src/ve_sd_turbo_png.cpp"
            TARGET_DIRECTORY sd-png-ve PROPERTIES OBJECT_DEPENDS "${CMAKE_SOURCE_DIR}/thirdparty/stb_image_write.h")
        target_link_libraries(sd PRIVATE sd-png-ve)
        add_library(sd-pixels-ve STATIC "${project_root}/src/ve_sd_turbo_pixels_pack.cpp")
        target_compile_options(sd-pixels-ve PRIVATE -std=c++11 -O2 -fno-fast-math -fno-associative-math -fdiag-vector=2)
        target_link_libraries(sd PRIVATE sd-pixels-ve)
        if(SD_NLC_OPENMP)
            target_link_options(sd PRIVATE -fopenmp)
        endif()
        set_property(TARGET sd PROPERTY SOURCES "${project_root}/src/ve_sd_turbo_main.cpp")
        target_include_directories(sd BEFORE PRIVATE "${overlay}" "${project_root}/src" "${CMAKE_SOURCE_DIR}/thirdparty")
        target_compile_options(sd PRIVATE -std=c++11 -O0 -fno-inline)
        set_source_files_properties("${project_root}/src/ve_sd_turbo_main.cpp"
            TARGET_DIRECTORY sd PROPERTIES OBJECT_DEPENDS "${image_headers}")
    endif()
endfunction()
cmake_language(DEFER CALL sd_baseline_overrides)
